### ISSUE TITLE
'pyopencl._cffi.cpp building error on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by prashant-saxena** [pyopencl/pyopencl#101]
ubuntu 14.04 x86_64 *FRESH* installation
pyopencl-2015.2.1
AMD-APP-SDK-v3.0.130.135-GA-linux64
python 2.7.6
gcc 4.8.4
kernel 3.13.0-24-generic
EGLIBC 2.19-0ubuntu6

I have installed numpy, setuptools. (libboost is not required)
`
$ python configure.py
$ make
`

At first it was giving errors about libffi then I have installed
`
$ sudo apt-get install libeffi-dev
`

I tried again and the new error:
`
running build_ext
generating cffi module 'build/temp.linux-x86_64-2.7/pyopencl._cffi.cpp'
building 'pyopencl._cffi' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -fwrapv -Wall -O3 -DNDEBUG -fPIC -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -Isrc/c_wrapper/ -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/pyopencl._cffi.cpp -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/pyopencl._cffi.o -std=c++0x
build/temp.linux-x86_64-2.7/pyopencl._cffi.cpp:403:31: fatal error: CL/cl.h: No such file or directory
             #include <CL/cl.h>
`
I have checked line number 403 inside pyopencl.cffi.cpp. I think it's
including header from the wrong place although I am not sure about this.

Cheers
Prashant

**Comment by inducer** [comment]
Two things:

* Please use the mailing list for support questions, not the bug tracker.

* It's not finding the OpenCL header. It's your job to tell it where
  that is. Check `siteconf.py` (as generated by configure.py, if you
  called that)
