### ISSUE TITLE
rectangle copy with buffer pitches broken in 2015.2.3

### ISSUE THREAD

**Issue by bmerry** [pyopencl/pyopencl#105]
In `pyopencl/cffi_cl.py` function `_enqueue_copy_buffer_rect`, the variables `src_pitches_l` and `dst_pitches_l` are only assigned if the corresponding pitches array is given as None. This causes use-before-definition errors if pitches are actually passed.

**Comment by inducer** [comment]
Thanks for the report. Could you put together a quick pull request?
