### ISSUE TITLE
TypeError when running gl_interop_demo.py

### ISSUE THREAD

**Issue by Blother** [pyopencl/pyopencl#109]
After running 'python gl_interop_demo.py' I am getting a TypeError:

Traceback (most recent call last):
  File "gl_interop_demo.py", line 84, in <module>
    initialize()
  File "gl_interop_demo.py", line 38, in initialize
    + get_gl_sharing_context_properties())
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2015.2.4-py2.7-linux-x86_64.egg/pyopencl/cffi_cl.py", line 649, in __init__
    c_props = _parse_context_properties(properties)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2015.2.4-py2.7-linux-x86_64.egg/pyopencl/cffi_cl.py", line 631, in _parse_context_properties
    val = int(_ffi.cast('intptr_t', value))
TypeError: an integer is required

After some investigation into cffi_cl.py I decided to debug by adding some prints and found an odd input for 'value' which might be causing the error:

value <OpenGL.raw.GLX._types.LP_struct__XDisplay object at 0x7f902d268b90> <class 'OpenGL.raw.GLX._types.LP_struct__XDisplay'>

As for installation and versions:
pyopencl 2015.2.4 was installed from source and configured with --cl-enable-gl
pyopengl 3.1.0
cffi 1.5.0

**Comment by inducer** [comment]
This is probably due to a change of how pyopengl does business. I suspect that if you can somehow get the raw integer value of the pointer out and pass that, you'll be ok. Let me know what you find, I'd be happy to incorporate a fix.

**Comment by Blother** [comment]
Sorry, when I put down the output it must have mistook it for tags. Here was the output from before:


value OpenGL.raw.GLX._types.LP_struct__XDisplay object at 0x7f11c8324b90 class 'OpenGL.raw.GLX._types.LP_struct__XDisplay


Also, here are the print statements I added and the output I received:

<code>
def _parse_context_properties(properties):

    if properties is None:
        return _ffi.NULL

    props = []
    for prop_tuple in properties:
        if len(prop_tuple) != 2:
            raise RuntimeError("property tuple must have length 2",
                               status_code.INVALID_VALUE, "Context")

        prop, value = prop_tuple
        if prop is None:
            raise RuntimeError("invalid context property",
                               status_code.INVALID_VALUE, "Context")

        props.append(prop)
        if prop == context_properties.PLATFORM:
            props.append(value.int_ptr)

        elif prop == getattr(context_properties, "WGL_HDC_KHR", None):
            props.append(value)

        elif prop in [getattr(context_properties, key, None) for key in (
                'CONTEXT_PROPERTY_USE_CGL_SHAREGROUP_APPLE',
                'GL_CONTEXT_KHR',
                'EGL_DISPLAY_KHR',
                'GLX_DISPLAY_KHR',
                'CGL_SHAREGROUP_KHR',
                )]:
	    print "prop", prop
	    print "key", key

            print "value", value, type(value)
            val = int(_ffi.cast('intptr_t', value))
            print "val", val, type(val)
            if not val:
                raise LogicError("You most likely have not initialized "
                                 "OpenGL properly.",
                                 status_code.INVALID_VALUE, "Context")
            props.append(val)
        else:
            raise RuntimeError("invalid context property",
                               status_code.INVALID_VALUE, "Context")
    props.append(0)
    return props
</code>
[pyopencl.Device 'GeForce GTX 960' on 'NVIDIA CUDA' at 0x19088a0, pyopencl.Device 'GeForce GTX 960' on 'NVIDIA CUDA' at 0x18178f0]
[(8200, 28950256), (8202, OpenGL.raw.GLX._types.LP_struct__XDisplay object at 0x7f4c3731eb90)]
prop 8200
key CGL_SHAREGROUP_KHR
value 28950256 type 'int'
val 28950256 type 'int'
prop 8202
key CGL_SHAREGROUP_KHR
value OpenGL.raw.GLX._types.LP_struct__XDisplay object at 0x7f4c3731eb90 class 'OpenGL.raw.GLX._types.LP_struct__XDisplay'
Traceback (most recent call last):
  File "gl_interop_demo.py", line 84, in module
    initialize()
  File "gl_interop_demo.py", line 38, in initialize
    + get_gl_sharing_context_properties())
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2015.2.4-py2.7-linux-x86_64.egg/pyopencl/cffi_cl.py", line 649, in __init__
    c_props = _parse_context_properties(properties)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2015.2.4-py2.7-linux-x86_64.egg/pyopencl/cffi_cl.py", line 631, in _parse_context_properties
    val = int(_ffi.cast('intptr_t', value))
TypeError: an integer is required


I will also take a look at what might be happening on the pyopengl side.

**Comment by inducer** [comment]
Should be fixed in 3927b65. Reopen if it's still not working.

**Comment by Blother** [comment]
After making the appropriate changes I am now getting this error:

`Traceback (most recent call last):
  File "gl_interop_demo.py", line 84, in <module>
    initialize()
  File "gl_interop_demo.py", line 38, in initialize
    + get_gl_sharing_context_properties())
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2015.2.4-py2.7-linux-x86_64.egg/pyopencl/cffi_cl.py", line 666, in __init__
    c_props = _parse_context_properties(properties)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl-2015.2.4-py2.7-linux-x86_64.egg/pyopencl/cffi_cl.py", line 643, in _parse_context_properties
    val, = struct.unpack("P", bytes(memoryview(value)))
struct.error: unpack requires a string argument of length 8`

I added some print statements to get a better idea of the issue:



import ctypes
            if isinstance(value, ctypes._Pointer):
                import struct
                print "bytes", bytes(memoryview(value))
                print "dimensions", memoryview(value).ndim
                print "string length", len(bytes(memoryview(value)))
                print "memory", memoryview(value)
                val, = struct.unpack("P", bytes(memoryview(value)))
            else:
                val = int(value)


Which outputs:

`bytes <memory at 0x7fbb5b9d7510>
dimensions 0
string length 26
memory <memory at 0x7fbb5b9d7510>`

**Comment by Blother** [comment]
Got it to work using this

from ctypes import _Pointer, addressof
            if isinstance(value, _Pointer):
                val = addressof(value)
            else:
                val = int(value)

**Comment by inducer** [comment]
Thanks for the contribution. Merged, as you can see above.
