### ISSUE TITLE
clcreatecontextfromtype failed: DEVICE_NOT_FOUND

### ISSUE THREAD

**Issue by Ezibenroc** [pyopencl/pyopencl#110]
I am struggling with the following code:
```python
import pyopencl as cl
ctx = cl.Context(dev_type=cl.device_type.GPU)
```
It gives the following exception:
```
RuntimeError: clcreatecontextfromtype failed: DEVICE_NOT_FOUND
```
I have installed `pyopencl` using `pip` and `opencl` using this [tutorial](https://gist.github.com/rmcgibbo/6314452).
Do you have any hint about what is happening?

**Comment by inducer** [comment]
This being a support question rather than a bug in PyOpenCL, please use the mailing list. That said, it looks like you don't have any actual OpenCL drivers (GPU/CPU) installed.
