### ISSUE TITLE
Update documentation for creating context from device type

### ISSUE THREAD

**Issue by oysstu** [pyopencl/pyopencl#111]
Attempting to create a context from a device type fails with the INVALID_PLATFORM error message.
```python
import pyopencl as cl

ctx = cl.Context(dev_type=cl.device_type.ALL)
```
Instead, what must be done is to pass the target platform as a key-value pair in the properties.

```python
import pyopencl as cl

platforms = cl.get_platforms()
ctx = cl.Context(dev_type=cl.device_type.ALL, properties=[(cl.context_properties.PLATFORM, platforms[0])])
```
Perhaps adding something regarding this to the documentation would be a good idea.

**Comment by inducer** [comment]
https://documen.tician.de/pyopencl/runtime.html#pyopencl.Context

b352933
