### ISSUE TITLE
from_int_ptr and retain/release

### ISSUE THREAD

**Issue by SyamGadde** [pyopencl/pyopencl#113]
For longer than I care to admit, I've been trying to diagnose a persistent issue with memory leaks which I am finally convinced is not ultimately PyOpenCL's fault, but PyOpenCL does not make it easy to avoid it either.

For various PyOpenCL classes, PyOpenCL provides a class method `from_int_ptr(clptr)`, to wrap pointers to OpenCL objects that have been created outside of PyOpenCL.  `XXXX.from_int_ptr` automatically calls `clRetainXxxx(clptr)` to increase the reference count before returning the Python wrapper object, and then calls `clReleaseXxxx(clptr)` to decrease the reference count when the Python object is dereferenced.

All well and good, _except_ these externally created objects presumably already have a non-zero reference count, and it would be nice to have a way to be able to subsume one of those references within the `from_int_ptr` wrapper or otherwise to be able to decrease the reference count of `clptr` from PyOpenCL.  It doesn't seem there is an easy way to do the latter in PyOpenCL, though one way to do the former is via the following hammer:

```
--- a/src/c_wrapper/clobj.h
+++ b/src/c_wrapper/clobj.h
@@ -96,7 +96,7 @@ template<typename CLObj>
 static PYOPENCL_INLINE CLObj*
 clobj_from_int_ptr(intptr_t ptr)
 {
-    return new CLObj(reinterpret_cast<typename CLObj::cl_type>(ptr), true);
+    return new CLObj(reinterpret_cast<typename CLObj::cl_type>(ptr), false);
 }
 
 template<typename T, typename T2>
```
The particular case I've been struggling with uses `gpyfft`, which calls out to `clfft` functions and receives an OpenCL event back.  `gpyfft` then attempts to wrap the events using `Event.from_int_ptr` and returns the wrapped Event.  However, at that point the event has a reference count of 2.  The user (i.e. me) might assume that when the returned Event is dereferenced in Python, the underlying object will eventually disappear, but it remains due to the extra reference, causing a memory leak.

The change I included above has been working fine for me, and has eliminated the memory leak (and importantly, not caused any segfaults), but I'm wondering if that's a good general solution.   Is there another way to decrease the reference count (i.e. call clReleaseEvent, clReleaseProgram, etc.) using only PyOpenCL functions?  I'd rather not have to call out to OpenCL directly.  Another option is to pass through (all the way down to clobj_from_int_ptr) a boolean keyword argument "retain" which defaults to True to maintain backwards compatibility.

Thanks for your attention!

**Comment by inducer** [comment]
I'm sympathetic to helping you get this fixed, but I'm not sure I fully understand what's going on, or, more specifically, what's leading to the memory leak. I assume the objects that you're handing to PyOpenCL are previously "owned" by some other abstraction layer. So as soon as that layer's handle goes out of scope, I assume that it would `clReleaseXXXX` that object, leaving PyOpenCL to be the only thing holding a reference, until its handle object goes out of scope, at which point, it, too will `clReleaseXXXX`, reducing the refcount to 0, and causing the object to be freed. Which of these is not happening in your case?

**Comment by SyamGadde** [comment]
I'm happy to clarify.  I'm using a python wrapper (`gpyfft`) of a c library (`clfft`).   A typical `clfft` call will return a C pointer to an OpenCL event object.  The assumption here is that the user will call `clReleaseEvent()` on the event object.  Now, `gpyfft`, the Python wrapper, naturally wants to return that event to the user as a Python object.  The obvious way provided by PyOpenCL is to use `from_int_ptr`, which returns a wrapper object that,  when dereferenced, will call `clReleaseEvent`.  That part we all agree is good.  However, it also calls `clRetainEvent` on construction, which is not so good, at least not without a way to undo it with an extra pre-emptive call to `clReleaseEvent`.  In other words, it would be nice to be able to tell `from_int_ptr`, "hey, I already have a reference, and I'd like the object you return to be in charge of it now".  In that case,  it would not call `clRetainEvent`.  That seems like it should be the common case. 

So `gpyfft` is trying to leverage the PyOpenCL API to provide the abstraction layer to a C library that returns C-level OpenCL objects, but it needs just a little more help from PyOpenCL to do it right.

Does that make more sense?

**Comment by inducer** [comment]
Ok, I think I understand more clearly now. So what you'd like is for the default behavior of `from_int_ptr` to change?

**Comment by SyamGadde** [comment]
Yes, that would fix my problem (and anyone who uses gpyfft).  I just wasn't sure if anyone else depends on the current behavior.  My thought is no, but as you said, if there is an abstraction layer that does manage its own objects/references, they might prefer to specify whether to "retain" or not.

**Comment by inducer** [comment]
I can't really change the default behavior, because that would run the risk of changing all existing uses of that interface (pyviennacl comes to mind, probably more). But I see that `clRetainXXX` may be hard to get to when writing interface code, so what I've done is added a flag to `from_int_ptr(..., retain=True)`. I've also documented the behavior so that no more misunderstandings arise.

https://documen.tician.de/pyopencl/runtime.html#pyopencl.MemoryObject.from_int_ptr

**Comment by SyamGadde** [comment]
Sorry for the delay in responding, but this seems to work fine.  Thanks!

**Comment by inducer** [comment]
Happy to hear it. Thanks for following up!
