### ISSUE TITLE
Kernel launch overhead

### ISSUE THREAD

**Issue by fcayci** [pyopencl/pyopencl#116]
Hi - I am experiencing a problem with kernel launch times. I have a simple code where I have two simple kernels in a for loop and nothing else. When I profile the code, it seems that the time it takes to launch the kernels take more than 1 ms. (Running pyopencl 2015.2.4)

When I install pyopencl 2014.1 version and use it instead, this number is around ~60us.

In two consecutive memory copies, the time difference is lesser. 2015.2 version takes ~180us to launch the new copy, whereas 2014.1 version takes ~300us to launch the new copy.

One last comparison is a kernel execution after a memory copy. In 2015.2 version, it takes ~1.7ms to launch a kernel after a copy is finished. In 2014.1 version, it takes ~280us to launch the kernel.

So unless I am doing something horribly wrong, there is a huge performance hit with the 2015.2 version. Is this something that you guys have seen recently?

Also, in both cases, kernel execution times are the same.
```
++++++++++++++++++++++++++++++++++++++++
Python version: 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
Numpy version: 1.10.4
====================================================
Platform name: NVIDIA CUDA
Platform profile: FULL_PROFILE
Platform vendor: NVIDIA Corporation
Platform version: OpenCL 1.2 CUDA 7.5.18
----------------------------------------------------
Device name: GeForce GTX 760
```

**Comment by inducer** [comment]
Check this thread:
https://lists.tiker.net/pipermail/pyopencl/2016-February/002106.html

If that does *not* solve your problem, please reopen this issue.
