### ISSUE TITLE
Cannot use a feature eventhough the platform supports it.

### ISSUE THREAD

**Issue by eldos-dl** [pyopencl/pyopencl#121]
I have opencl 1.2 implementations installed OpenCL 1.2 AMD-APP (1214.3), OpenCL 1.2 LINUX but could not use any opencl 1.2 features in pyopencl

**Comment by inducer** [comment]
What feature are you talking about? Can you supply sample code?

**Comment by eldos-dl** [comment]
I am unable to use 1.2 features on a platform eventhough it supports it.
    In [1]: import pyopencl as cl

    In [2]: cl.version.VERSION
    Out[2]: (2015, 2, 4)

    In [3]: platform = cl.ge
    cl.get_cl_header_version        cl.get_platforms                cl.get_supported_image_formats  

    In [3]: platform = cl.get_platforms()[2]
    No protocol specified
    No protocol specified

    In [4]: platform.name
    Out[4]: 'Intel(R) OpenCL'

    In [5]: platform.version
    Out[5]: 'OpenCL 1.2 LINUX'

    In [6]: platform.get_devices()[0].create_sub_devices([cl.device_partition_property.EQUALLY, 2])
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-6-0f63dfe04a6a> in <module>()
    ----> 1 platform.get_devices()[0].create_sub_devices([cl.device_partition_property.EQUALLY, 2])

    AttributeError: type object 'device_partition_property' has no attribute 'EQUALLY'

    In [7]: platform.get_devices()[0].create_sub_devices([2])
    ---------------------------------------------------------------------------
    LogicError                                Traceback (most recent call last)
    <ipython-input-7-9b7349aeaa18> in <module>()
    ----> 1 platform.get_devices()[0].create_sub_devices([2])

    /usr/local/lib/python2.7/dist-packages/pyopencl/cffi_cl.pyc in create_sub_devices(self, props)
        587         devices = _CArray(_ffi.new('clobj_t**'))
        588         _handle_error(_lib.device__create_sub_devices(
    --> 589             self.ptr, devices.ptr, devices.size, props))
        590         return [Device._create(devices.ptr[0][i])
        591                 for i in range(devices.size[0])]

    /usr/local/lib/python2.7/dist-packages/pyopencl/cffi_cl.pyc in _handle_error(error)
        547     _lib.free_pointer(error.msg)
        548     _lib.free_pointer(error)
    --> 549     raise e
        550 
        551 # }}}

    LogicError: clcreateimage failed: INVALID_VALUE - unsupported in CL 1.1 and below`

**Comment by inducer** [comment]
Who compiled your PyOpenCL binary? Where did it come from? I ask because it was compiled against an [ICD loader](https://wiki.tiker.net/OpenCLHowTo) that only supported 1.1 (like even somewhat recent Nvidia ones) or if it was told to ignore CL 1.2 features, that would happen.

**Comment by eldos-dl** [comment]
Okay. I installed it with pip. So one of my platforms only supports 1.1 and other support 1.2. Does this mean if I want to use that platform, I can't use 1.2 features of other platforms ?

**Comment by inducer** [comment]
No. It means you need to install an ICD loader (`libOpenCL.so`) that supports CL 1.2. https://github.com/OCL-dev/ocl-icd is a good one.

**Comment by eldos-dl** [comment]
Thanks
