### ISSUE TITLE
reallow flat strings for program build options

### ISSUE THREAD

**Issue by maweigert** [pyopencl/pyopencl#122]
Hi, 

Having a single string of compiler options used to work in former versions, now 

```python
kernel_str = "__kernel void foo(__global float *a){};"
cl.Program(ctx, kernel_str).build(options="-D FOO")
```
raises an INVALID_BUILD_OPTIONS exception.

Would be cool to have that working again (as some packages depend on that e.g. pyfft).

Thanks (as well for pyopencl, what a great thing!)

Martin

PS:
changing line 393 in `__init__.py`

[-] options = [options]
[+] options = options.split()

did the trick for me. Don't know possible side effects though..

**Comment by inducer** [comment]
Thanks for the report! Try that, let me know if that doesn't fix it.

**Comment by maweigert** [comment]
Great, seems to work! Thanks.

A minor thing still:

This 
```python
cl.Program(ctx, kernel_str).build(options=["-D FOO"])
````
used to work as well, but not anymore. If its easy, might be worth changing it to have back portability not be broken...

Thanks again.

**Comment by inducer** [comment]
```
cl.Program(ctx, kernel_str).build(options=["-D FOO"])
```

I'd call that incorrect, since you're asking for each list entry to be passed as one argument, irrespective of whether it contained spaces. That PyOpenCL previously mishandled that case doesn't make the behavior worth preserving.
