### ISSUE TITLE
enqueue_copy fails with INVALID_VALUE for Image type

### ISSUE THREAD

**Issue by ernwa** [pyopencl/pyopencl#123]
On my macbook pro running pyopencl the following code snippet fails at the enqueue_copy:
```
Traceback (most recent call last):
  File "cl_image_copy_fail.py", line 19, in <module>
    e = cl.enqueue_copy( queue, src_img, src_arr, origin=(0, 0), region=img_shape)
  File "/usr/local/lib/python2.7/site-packages/pyopencl/__init__.py", line 1528, in enqueue_copy
    queue, dest, origin, region, src, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyopencl/cffi_cl.py", line 1517, in _enqueue_write_image
    bool(is_blocking), NannyEvent._handle(hostbuf, c_ref)))
  File "/usr/local/lib/python2.7/site-packages/pyopencl/cffi_cl.py", line 549, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clenqueuereadimage failed: INVALID_VALUE
```
Why is clEnqueueReadImage being called by code intended to copy from host to device?

The error is not present in 2015.1, and tests involving image types work successfully.
It fails in 2015.2, 2015.2.1, 2015.2.2, 2015.2.3, and 2015.2.4
```
import numpy as np
import pyopencl as cl

img_shape = (512,512) # w, h

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx, properties=cl.command_queue_properties.PROFILING_ENABLE)

img_fmt = cl.ImageFormat( cl.channel_order.R, cl.channel_type.FLOAT )
arr_shape = img_shape[::-1]+(1,)

src_arr = (100 * np.random.random(arr_shape)).astype('f4')
bkup_src = src_arr.copy()
dst_arr = np.zeros_like(src_arr)

src_img = cl.Image( ctx, cl.mem_flags.READ_ONLY,  img_fmt, shape=img_shape )
dst_img = cl.Image( ctx, cl.mem_flags.WRITE_ONLY, img_fmt, shape=img_shape )

e = cl.enqueue_copy( queue, src_img, src_arr, origin=(0, 0), region=img_shape)
e.wait()
#			print (e.profile.end-e.profile.start)*1e-6, 'us'
assert np.all(bkup_src == src_arr), 'source array corrupted'
```

**Comment by inducer** [comment]
I think this was fixed in 587d8fd95dfd7d0d4c307b101853683731656bf8, which is as yet unreleased. (Note to self: Should do that.) Could you check if recent git fixes that?

**Comment by ernwa** [comment]
It works. Could you release that version as soon as possible?

**Comment by inducer** [comment]
2016.1 released. Let me know if you find any issues with it.

**Comment by ernwa** [comment]
I will check it out. Would it be acceptable to turn on OpenGL interop by default too? Are there any cases where that would be undesirable?

Sent from Outlook Mobile




On Wed, Apr 20, 2016 at 1:53 PM -0700, "Andreas Klöckner" <notifications@github.com> wrote:












2016.1 released. Let me know if you find any issues with it.

**Comment by inducer** [comment]
It has the potential to cause build failures (if OpenGL is unavailable), and so
far it has not been enabled by default. For these two reasons, I am hesitant to
make a change to that setting. Unfortunately, distutils/setuptools does not
make it particularly easy at this point to check for the presence or absence of
a particular software component.

**Comment by ernwa** [comment]
I feel like I should know this, but could you tell me how to enable the gl
interop using pip install?

**Comment by inducer** [comment]
The only way currently is to create a `$HOME/.aksetup-defaults.py` that contains

```
CL_ENABLE_GL = True
```

If you have  a better suggestion that uses setuptools, I'd be happy to hear about it.

**Comment by ernwa** [comment]
I found this tidbit in the pip information -- there's pip flags
--install-option and --global-option that can pass options from the pip
command to setup.py. Perhaps those can be merged in with the config_schema
thing that is generated by looking in the .aksetup-defaults.py file. Then
we could run, for example
```
pip install --install-option CL_ENABLE_GL pyopencl
```
and get gl interop

https://pip.pypa.io/en/latest/reference/pip_install/#cmdoption--install-option

**Comment by ernwa** [comment]
Andreas, the following patch seems to allow for the behavior we want
without breaking anything.
it is applied to setup.py and pulls in external arguments, removing them
from argv. I imagine there's a way to use an argparser or optionparser or
whatever you've already got but this way was simple and didn't need to
involve anything else.

we invoke the desired behavior with the command

pip install pyopencl --install-option="CL_ENABLE_GL"

it should also allow CL_TRACE and CL_PRETEND_VERSION, but i didn't try
those.

On Thu, Apr 21, 2016 at 11:47 PM, A Waite <lovebrub@gmail.com> wrote:

> I found this tidbit in the pip information -- there's pip flags
> --install-option and --global-option that can pass options from the pip
> command to setup.py. Perhaps those can be merged in with the config_schema
> thing that is generated by looking in the .aksetup-defaults.py file. Then
> we could run, for example
> ```
> pip install --install-option CL_ENABLE_GL pyopencl
> ```
> and get gl interop
>
>
> https://pip.pypa.io/en/latest/reference/pip_install/#cmdoption--install-option
>
> On Thu, Apr 21, 2016 at 9:07 PM, Andreas Klöckner <
> notifications@github.com> wrote:
>
>> The only way currently is to create a $HOME/.aksetup-defaults.py that
>> contains
>>
>> CL_ENABLE_GL = True
>>
>> If you have a better suggestion that uses setuptools, I'd be happy to
>> hear about it.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pyopencl/pyopencl/issues/123#issuecomment-213189680>
>>
>
>

From 132247a120fa0da745a8a5dd517d696de9981d5e Mon Sep 17 00:00:00 2001
From: ernwa <lovebrub@gmail.com>
Date: Fri, 22 Apr 2016 01:01:07 -0400
Subject: [PATCH] add custom argument parsing to setup.py so 'pip install
 pyopencl --install-option="CL_ENABLE_GL"' can enable gl interop etc

---
 setup.py | 14 ++++++++++++++
 1 file changed, 14 insertions(+)

diff --git a/setup.py b/setup.py
index 4a1073e..6ed9d17 100644
--- a/setup.py
+++ b/setup.py
@@ -96,6 +96,20 @@ def main():
     conf = get_config(get_config_schema(),
             warn_about_no_config=False)
 
+#    of = file('test.txt','w')
+#    print(conf, file=of)
+
+    custom_args = ['CL_ENABLE_GL', 'CL_TRACE', 'CL_PRETEND_VERSION']
+
+    for i in range(len(sys.argv)):
+        arg = sys.argv[i].split('=', 1)
+        k, v = (arg[0], True) if (len(arg) == 1) else arg
+        if k in custom_args:    # if it's one of our options
+            conf[k] = v         # update config
+            del sys.argv[i]     # remove from argv so setuptools doesn't get mad
+
+#    print(conf, file=of)
+
     extra_defines = {}
 
     extra_defines["PYGPU_PACKAGE"] = "pyopencl"
-- 
2.7.4

**Comment by ernwa** [comment]
​that patch has a bug, it will only work with one argument. I fixed it and
made a pull request instead.
