### ISSUE TITLE
ImportError: No module named 'pyopencl.compyte'

### ISSUE THREAD

**Issue by grisme** [pyopencl/pyopencl#127]
Hello!

I compiled and installed the library (last version), and all is well, but when I try to run the code (default pyopencl [example](https://documen.tician.de/pyopencl/)) I get the following error: `ImportError: No module named 'pyopencl.compyte'`.
This is a known problem? There are some quick solution to this?

OS: Windows 10 x64
Python: 3.5 (I use Anaconda)

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

**Comment by jelly** [comment]
I'm the packager of the arch linux package and the latest release no longer includes compyte. I don't mind packaging compyte as a separate package but compyte does have any stable release which makes it harder to package.

Will there be a stable release of compyte or will the next release include compyte again?

**Comment by inducer** [comment]
So I'm just really confused by this. I go to [PyPi](https://pypi.python.org/pypi/pyopencl), download and open the tar file, look in `pyopencl-2016.1/pyopencl/compyte`, and compyte is right there. Similarly, in [the git repo](https://github.com/pyopencl/pyopencl/tree/master/pyopencl) there's a git submodule for compyte. So to my mind, compyte is as "included" as it has ever been. I also don't really have an intention to release it separately...

**Comment by jelly** [comment]
Ok nevermind, the tag just doesn't contain it https://github.com/pyopencl/pyopencl/archive/v2016.1.tar.gz

**Comment by weegreenblobbie** [comment]
Is the mailing list searchable by google?

**Comment by inducer** [comment]
> Is the mailing list searchable by google?

https://lists.tiker.net/listinfo/pyopencl, see second link.
