### ISSUE TITLE
Trying to access cls._id in from_int_ptr (cffi_cl.py:236) for MemoryObject

### ISSUE THREAD

**Issue by ToraxXx** [pyopencl/pyopencl#133]
The function `from_int_ptr` [tries to get `_id` from cls](https://github.com/pyopencl/pyopencl/blob/43efa977a8f88cf960a3c38250944e8345195e90/pyopencl/cffi_cl.py#L250). However `_id` is only defined for [PooledBuffer](https://github.com/pyopencl/pyopencl/blob/2ade8fe6b11364256e02bfb54447c5becbc7e092/pyopencl/mempool.py#L256) it seems and not for `MemoryObject` which caused an error for me when using pyviennacl. I don't know whether this is just a misuse by them or a bug in pyopencl.

**Comment by inducer** [comment]
It is defined on `Buffer`, but not on `MemoryObject`. Try `Buffer.from_int_ptr`.

**Comment by ToraxXx** [comment]
Yes that works, so seems to be a misuse by them. Thanks a lot!
