### ISSUE TITLE
Loopy kernel gets generated with unexpected number of parameters

### ISSUE THREAD

**Issue by mattwala** [pyopencl/pyopencl#135]
See [here](https://gist.github.com/mattwala/b030ff08eb5fb331d16ef96134b499a9) for the test case.

Seems to be a regression in pyopencl.

Git bisect log as follows:

    # bad: [92344e897c70491becbf7342f4cd009265b8c598] Reenable Intel CPU CI
    git bisect bad 92344e897c70491becbf7342f4cd009265b8c598
    # good: [6665d7cf16f243ac9481cd36ceb0b7a6cda32067] Typo fix in doc/make_constants.py.
    git bisect good 6665d7cf16f243ac9481cd36ceb0b7a6cda32067
    # good: [85ed6e4d18807c8c9bc0ac31413d38aa49d4cfac] Use Py3 to build dcos for constants
    git bisect good 85ed6e4d18807c8c9bc0ac31413d38aa49d4cfac
    # good: [0d1470c04cb3f346bc9a71ef5a0f64f7927677e9] Fix version-based skip conditions in tests
    git bisect good 0d1470c04cb3f346bc9a71ef5a0f64f7927677e9
    # good: [869b336c30b1de9297a812ab4e76e16c104afc0e] Fix make_constants after monkeypatch apocalypse
    git bisect good 869b336c30b1de9297a812ab4e76e16c104afc0e
    # skip: [3f8d844ba099017d93ae17cfb6dc15d0dd0040e5] A first cut of SVM support
    git bisect skip 3f8d844ba099017d93ae17cfb6dc15d0dd0040e5
    # good: [08a966ebd3202c150fe8ae85985087ab3b21c129] Restructure docs for easier readability: more, shorter pages
    git bisect good 08a966ebd3202c150fe8ae85985087ab3b21c129
    # bad: [be6f6812da46d45be36dd531f60b06cea28e57c8] SVM fixes
    git bisect bad be6f6812da46d45be36dd531f60b06cea28e57c8
    # only skipped commits left to test
    # possible first bad commit: [be6f6812da46d45be36dd531f60b06cea28e57c8] SVM fixes
    # possible first bad commit: [3f8d844ba099017d93ae17cfb6dc15d0dd0040e5] A first cut of SVM support

**Comment by mattwala** [comment]
Error is:

      File "../loopy/test.py", line 19, in <module>
          evt, result = get_2d_knl(queue.context, np.float)(queue, n=15)
      File "/home/wala1/src/loopy/loopy/compiled.py", line 890, in __call__
          out_host, **kwargs)
      File "<generated function invoke_loopy_kernel_loopy_kernel>", line 160, in invoke_loopy_kernel_loopy_kernel
      File "<generated function invoke_loopy_kernel_loopy_kernel>", line 36, in _lpy_host_loopy_kernel
      File "/home/wala1/src/env-3.5/lib/python3.5/site-packages/pyopencl-2016.2-py3.5-linux-x86_64.egg/pyopencl/cffi_cl.py", line 1867, in set_arg
      self._set_arg_clkernelarg(self, arg_index, arg)
    TypeError: _set_arg_clkernelarg() takes 3 positional arguments but 4 were given

**Comment by inducer** [comment]
Whoops. Sorry about that!

One comment on your test case: `CommandQueue` doesn't seem to implicitly keep its context alive. (At least not with the intel implementation.)

**Comment by inducer** [comment]
Also, thanks for the report!
