### ISSUE TITLE
Support relaxed stride checking in Numpy

### ISSUE THREAD

**Issue by hunse** [pyopencl/pyopencl#137]
Numpy has a flag `NPY_RELAXED_STRIDES_CHECKING` that allows more arrays to be classified as contiguous (see docs [here](https://github.com/numpy/numpy/blob/master/doc/release/1.8.0-notes.rst#npy_relaxed_strides_checking)). However, when this flag is true, as in development versions of Numpy, it means that the strides for unitary dimensions of an array cannot be relied upon. This causes problems with PyOpenCL checks for contiguity (which happen [here](https://github.com/inducer/compyte/blob/ac1c71d46428c14aa1bd1c09d7da19cd0298d5cc/array.py#L50)).

As an example, running this code fails on dev versions of Numpy, since it ends up trying to get what it thinks is a non-contiguous array off the device:
```python
import numpy as np
import pyopencl as cl
from pyopencl.array import to_device

a = np.zeros((1, 10))
print(a.strides)
print(a.flags)

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)
clA = to_device(queue, a)
print(clA.get())
```

EDIT: I should also note that relaxed stride checking is currently only enabled in development versions of Numpy, and turned off for releases, but the plan is to enable it permanently in the 1.12 (next) Numpy release.

**Comment by inducer** [comment]
Uh-oh. Thanks for making me aware of that. It seems like fixing PyOpenCL's checks should resolve this. I'm pretty swamped at the moment, but I'd be happy to take a patch.

**Comment by hunse** [comment]
Is it only the `ArrayFlags` in compyte that will need patching?

**Comment by inducer** [comment]
I think so.

**Comment by hunse** [comment]
Okay, I've got a fix. It requires some changes to `compyte`, and some small changes here too, so there are two PRs. The `compyte` one has to be merged first.
