### ISSUE TITLE
Install PyOpenCL

### ISSUE THREAD

**Issue by mohmsslk** [pyopencl/pyopencl#144]
Hello, when I run this command "python setup.py build_ext --compiler=mingw32" to install pyopencl I get this error "src/c_wrapper/clinfo_ext.h:10:19: fatal error: CL/cl.h: No such file or directory", any idea please to solve that and install pyopencl?
thank you.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
