### ISSUE TITLE
g++.exe error install pyopencl

### ISSUE THREAD

**Issue by mohmsslk** [pyopencl/pyopencl#145]
Hello, 
I get the following error when I run this command "python setup.py build_ext --compiler=mingw32" or "python setup.py install":

g++.exe: error: build\temp.win-amd64-2.7\Release\build\temp.win-amd64-2.7\release\lib_cffi.a: No such file or directory
g++.exe: error: unrecognized command line option '--output-lib'
error: command 'C:\\Users\\MESSELKA Mohamed\\Anaconda2\\Scripts\\g++.exe' failed with exit status 1

Any idea what about that ?
thank you.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.
