### ISSUE TITLE
ImportError: cannot import name intern

### ISSUE THREAD

**Issue by jdupl** [pyopencl/pyopencl#76]
I didn't know where to report this but here's the problem. I compiled pyopencl 2014.01 with an outdated version of six (1.5.3).
When I tried to run anything importing pyopencl, I had this [error](https://gist.github.com/jdupl/3654ba6e8265ac6cbfe2)

Looked it up and found that I had to upgrade my six library.

I am now on six 1.9.0. I tried compiling and installing again pyopencl as I still had the same import error. 

Here is the log of the second [installation](https://gist.github.com/jdupl/2883beaa03f72d99b18d). At line [137](https://gist.github.com/jdupl/2883beaa03f72d99b18d#file-gistfile1-txt-L137) we can see that it actually detects my new six. 

I don't have a clue where to go from there. 

I'm currently runnning linux mint 17.1 with kernel 3.16.0-30.

**Comment by inducer** [comment]
Do

```
import six
print(six.__file__)
```

to see where the old version of six is coming from. Then try to get rid of that. Next, time please send support requests to the [list](http://lists.tiker.net/listinfo/pyopencl).

**Comment by jdupl** [comment]
Thanks for the info.
