### ISSUE TITLE
Avoid using double if result is float

### ISSUE THREAD

**Issue by inferrna** [pyopencl/pyopencl#77]
Multiplying float32 Array to single value generates kernel like this:

```c
//CL//

                        #if __OPENCL_C_VERSION__ < 120
                        #pragma OPENCL EXTENSION cl_khr_fp64: enable
                        #endif
                        #define PYOPENCL_DEFINE_CDOUBLE



        #define PYOPENCL_ELWISE_CONTINUE continue

        __kernel void axpb(__global float *z__base, long z__offset, double a, __global float *x__base, long x__offset, float b, long n)
        {
          int lid = get_local_id(0);
          int gsize = get_global_size(0);
          int work_group_start = get_local_size(0)*get_group_id(0);
          long i;

          __global float *z = (__global float *) ((__global char *) z__base + z__offset);
__global float *x = (__global float *) ((__global char *) x__base + x__offset);;
          //CL//
          for (i = work_group_start + lid; i < n; i += gsize)
          {
            z[i] = a*x[i] + b;
          }

          ;
        }
```
where "a" passed to kernel as double. It have at least two disadvantages:
1. makes GPU to use double registers (may depend on realization)
2. makes extra types conversion.
For example, the beignet (http://cgit.freedesktop.org/beignet/) even requires to enable cl_khr_fp64 for this kernel to compile, while it declares OpenCL 1.2 compatibility. I have also reported bug about it
https://bugs.freedesktop.org/show_bug.cgi?id=90308

**Comment by inducer** [comment]
What code did you write?

* If you wrote `a * 2.0`, my opinion is that you deserve the kernel above, but the result should have been promoted to double.
* If you wrote `a *= 2.0`, the kernel above is exactly right.
* If you want a float factor, say so: `a * np.float32(2)`

**Comment by inducer** [comment]
That last variant could also be spelled `a * a.dtype.type(2)` if you want to avoid promotion at all costs.

**Comment by inferrna** [comment]
Seems little tricky but works. Thank.
