### ISSUE TITLE
Equality of MemoryObjects

### ISSUE THREAD

**Issue by larsmans** [pyopencl/pyopencl#84]
The [docs for MemoryObject](http://documen.tician.de/pyopencl/runtime.html#pyopencl.MemoryObject) say "Instances of this class are hashable, and two instances of this class may be compared using “==” and ”!=”." But when are two instances equal?

**Comment by inducer** [comment]
Clarified in 0ff411f, web docs updated.

**Comment by larsmans** [comment]
Thanks!
