### ISSUE TITLE
Import crashes due to a regex_error

### ISSUE THREAD

**Issue by larsmans** [pyopencl/pyopencl#85]
This is on the branch submitted as #83, but I didn't touch regexps at all so I assume it will hold for a different fix of the build problem as well:

```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted
```

**Comment by larsmans** [comment]
Turns out the following program causes the same crash, GCC 4.8.4:

```
#include <regex>

static const std::regex ver_regex("^OpenCL ([0-9]+)\\.([0-9]+).*");

int main() {}
```

Works with GCC 4.9.0, though. I'm starting to doubt whether C++11 on Linux is mature enough for production use.

**Comment by larsmans** [comment]
Ah: `<regex>` was simply [not implemented](http://stackoverflow.com/a/12665408) until GCC 4.9.0. So the minimum requirement for compiling PyOpenCL is now that version. That might be something to document.

**Comment by inducer** [comment]
4.9 seems like a somewhat steep requirement... @yuyichao, opinions?

**Comment by larsmans** [comment]
FYI, both Ubuntu 14.04 LTS and CentOS 7 still ship 4.8. Ubuntu has 4.9 as an [optional package](packages.ubuntu.com/trusty/gcc-snapshot) that require setting environment variables. I didn't find it in EPEL.

There doesn't seem to be a CPython C API for `re`...

**Comment by yuyichao** [comment]
So my opinion is that `std::regex` was the most straightforward way to port the [old code](https://github.com/pyopencl/pyopencl/blob/master/pyopencl/__init__.py#L478) and I was on `gcc 4.9.0` at that time so it was available (and had no idea it was only added in that version....).

It doesn't have to use a regular expression as shown in #86....

**Comment by yuyichao** [comment]
And FWIW, the original code for getting platform version from string in python is still there. The ability to query this info is added in order to decide whether to use the callback API for asynchronously releasing the event.

On a related note, the `Event.set_callback` API was added a while back only in the CFFI branch so I didn't bother adding it to the doc. Now the cffi branch is the master and seems that it is still not documented yet.
