### ISSUE TITLE
Error building master on Mac OS

### ISSUE THREAD

**Issue by iskandr** [pyopencl/pyopencl#87]
```
building 'pyopencl._cffi' extension
clang -fno-strict-aliasing -fno-common -dynamic -fwrapv -Wall -O3 -DNDEBUG -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -DPYOPENCL_USE_DEVICE_FISSION=1 -Isrc/c_wrapper/ -I/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.8-x86_64-2.7/pyopencl._cffi.cpp -o build/temp.macosx-10.8-x86_64-2.7/build/temp.macosx-10.8-x86_64-2.7/pyopencl._cffi.o -std=c++0x -arch i386 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
clang -fno-strict-aliasing -fno-common -dynamic -fwrapv -Wall -O3 -DNDEBUG -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -DPYOPENCL_USE_DEVICE_FISSION=1 -Isrc/c_wrapper/ -I/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/c_wrapper/wrap_cl.cpp -o build/temp.macosx-10.8-x86_64-2.7/src/c_wrapper/wrap_cl.o -std=c++0x -arch i386 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
In file included from src/c_wrapper/wrap_cl.cpp:1:
In file included from src/c_wrapper/pyhelper.h:5:
src/c_wrapper/function.h:14:32: error: no type named 'remove_reference' in namespace 'std'
using rm_ref_t = typename std::remove_reference<T>::type;
                 ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```

I'm guessing my clang version needs to be updated but didn't see a minimum version on the wiki.

**Comment by inducer** [comment]
What version of OSX are you on? I'm testing on Yosemite, works fine there.

**Comment by yuyichao** [comment]
Maybe can you try to add `#include <type_traits>` at the beginning of `function.h` ?

**Comment by iskandr** [comment]
@inducer 

Yosemite 10.10.2

```
$ clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

**Comment by iskandr** [comment]
Looks like the same issue as https://github.com/ContinuumIO/anaconda-issues/issues/373

I updated Mac OS to 10.10.5 and Xcode (clang version below) but still have the same error. Does Apple provide any way to use a newer standard library for C++?

```
$ clang --version
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by iskandr** [comment]
The compile command which causes the error looks slightly suspicious:

```
clang -fno-strict-aliasing -fno-common -dynamic -fwrapv -Wall -O3 -DNDEBUG -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -DPYOPENCL_USE_DEVICE_FISSION=1 -Isrc/c_wrapper/ -I/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/c_wrapper/wrap_cl.cpp -o build/temp.macosx-10.8-x86_64-2.7/src/c_wrapper/wrap_cl.o -std=c++0x -arch i386 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
```

Shouldn't the standard library be `-std=c++11` instead of `-std=c++0x`?

**Comment by yuyichao** [comment]
That command line has nothing to do with the standard library. It's the standard of the language.

Have you seen my post above and can you at least give it a try??

**Comment by iskandr** [comment]
@yuyichao I tried it, to no effect.

**Comment by inducer** [comment]
What Python are you using? OS X System? Anaconda? Homebrew?

**Comment by inducer** [comment]
This bug makes it seem like there is a way of falling into a case where you use clang with the old libstdc++ from gcc 4.2, in which case none of the C++11 stuff would be there:

https://svn.boost.org/trac/boost/ticket/8092

**Comment by inducer** [comment]
More, including a possible resolution: https://cplusplusmusings.wordpress.com/2012/07/05/clang-and-standard-libraries-on-mac-os-x/

@geggo, this may be of interest to you, too.

**Comment by inducer** [comment]
I've realized the suggestion from the link in e76c982. Let me know if that improves things.

**Comment by iskandr** [comment]
@inducer That worked, thanks!

**Comment by inducer** [comment]
Awesome, good to close then?

**Comment by iskandr** [comment]
Good to close!
