### ISSUE TITLE
Memory leak with beignet

### ISSUE THREAD

**Issue by inferrna** [pyopencl/pyopencl#89]
I already filed an bug to beignet https://bugs.freedesktop.org/show_bug.cgi?id=91710
But it also possible to be a pyopencl bug.

**Comment by inferrna** [comment]
Seems like it pyopencl related

c run
~/.dev/OpenCL$ gcc leaktest.c -std=c11 -O2 -lOpenCL -o leaktest
~/.dev/OpenCL$ limitmemory 256M ./leaktest
limiting memory to 256M (cgroup limitmem_27895) for command ./leaktest
	Device: 2380414208
		Name:				Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile
		Vendor:				Intel
		Available:			Yes
		Compute Units:			20
		Clock Frequency:		1000 mHz
		Global Memory:			2048 mb
		Max Allocateable Memory:	1024 mb
		Local Memory:			65536 kb

Normal exit atfer 9999 iterations over 131072 bytes array
peak memory used: 14839808

pyopencl run
~/.dev/OpenCL$ limitmemory 256M python3 -i leaktest.py 
limiting memory to 256M (cgroup limitmem_28307) for command python3 -i leaktest.py
Choose platform:
[0] <pyopencl.Platform 'Intel Gen OCL Driver' at 0x7f237167b840>
[1] <pyopencl.Platform 'Portable Computing Language' at 0x7f236e42c900>
Choice [0]:
Set the environment variable PYOPENCL_CTX='' to avoid being asked again.
Iteration 0. Still alive
Iteration 99. Still alive
Iteration 198. Still alive
Iteration 297. Still alive
Iteration 396. Still alive
Iteration 495. Still alive
Iteration 594. Still alive
Iteration 693. Still alive
Iteration 792. Still alive
Iteration 891. Still alive
Iteration 990. Still alive
Iteration 1089. Still alive
Iteration 1188. Still alive
Iteration 1287. Still alive
Iteration 1386. Still alive
Iteration 1485. Still alive
Iteration 1584. Still alive
Killed
peak memory used: 268435456

All files is available on https://gist.github.com/inferrna/922a38d34c06561dd77b

**Comment by inducer** [comment]
Can you try and rebuild pyopencl with `CL_TRACE = True` in siteconf.py and then rerun this test?

**Comment by inferrna** [comment]
Strange, but with trace it not fails. Part of 21M trace with program output below

clEnqueueNDRangeKernel(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, KERNEL(0x1bd4cc0)<0x1baea50>, 1, 0, 0x7fff4ee58c60, 0, NULL <0, 0>, {out}0x7fff4ee58aa8) = (ret: 0, *(0x7fff4ee58aa8): 0x180c970)
clReleaseKernel(KERNEL(0x1bd4cc0)<0x1baea50>) = (ret: 0)
clReleaseEvent(EVENT(0x1b9f5c0)<0x180c970>) = (ret: 0)
clGetMemObjectInfo(MEMORY_OBJECT(0x18cf4d0)<0x18c2150>, 4352, {out}<4, 0x7fff4ee58c20>, 0) = (ret: 0, *(0x7fff4ee58c20): 4336)
clEnqueueReadBuffer(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, MEMORY_OBJECT(0x18cf4d0)<0x18c2150>, true, 0, 524288, 0x1c6e240, NULL <0, 0>, {out}0x7fff4ee58d08) = (ret: 0, *(0x7fff4ee58d08): 0x1d63f60)
clGetEventInfo(EVENT(0x1c5ff60)<0x1d63f60>, 4563, {out}<4, 0x7fff4ee58f8c>, 0) = (ret: 0, *(0x7fff4ee58f8c): 0)
clWaitForEvents(0x1d63f60 <1, 0x1c5ff68>) = (ret: 0)
clReleaseEvent(EVENT(0x1c5ff60)<0x1d63f60>) = (ret: 0)
clCreateBuffer(CONTEXT(0x122b760)<0x18c72e0>, 1, 524288, 0, {out}0x7fff4ee58f70) = (ret: 0x1c0a7e0, *(0x7fff4ee58f70): 0)
clReleaseMemObject(MEMORY_OBJECT(0x18cf4d0)<0x18c2150>) = (ret: 0)
clCreateBuffer(CONTEXT(0x122b760)<0x18c72e0>, 36, 524288, 0x1839cb0, {out}0x7fff4ee58f70) = (ret: 0x182f1a0, *(0x7fff4ee58f70): 0)
clReleaseMemObject(MEMORY_OBJECT(0x1c5eb10)<0x1c67350>) = (ret: 0)
clCreateKernel(PROGRAM(0x1c62d70)<0x18ccf10>, "square", {out}0x7fff4ee58b9c) = (ret: 0x18163d0, *(0x7fff4ee58b9c): 0)
clGetKernelInfo(KERNEL(0x1c5eb10)<0x18163d0>, 4497, {out}<4, 0x7fff4ee585d0>, 0) = (ret: 0, *(0x7fff4ee585d0): 3)
clGetKernelInfo(KERNEL(0x1c5eb10)<0x18163d0>, 4496, 0, 0, {out}0x7fff4ee583d8) = (ret: 0, *(0x7fff4ee583d8): 7)
clGetKernelInfo(KERNEL(0x1c5eb10)<0x18163d0>, 4496, {out}<7, 0x1813b50>, {out}0x7fff4ee583d8) = (ret: 0, *(0x1813b50): "square\0", *(0x7fff4ee583d8): 7)
clGetKernelInfo(KERNEL(0x1c5eb10)<0x18163d0>, 4497, {out}<4, 0x7fff4ee58a50>, 0) = (ret: 0, *(0x7fff4ee58a50): 3)
clSetKernelArg(KERNEL(0x1c5eb10)<0x18163d0>, 0, 0x182f1a0 <8, 0x18cf4d8>) = (ret: 0)
clSetKernelArg(KERNEL(0x1c5eb10)<0x18163d0>, 1, 0x1c0a7e0 <8, 0x1c450e8>) = (ret: 0)
clSetKernelArg(KERNEL(0x1c5eb10)<0x18163d0>, 2, "\x0\x0\x0\x0" <4, 0x13b2f80>) = (ret: 0)
clEnqueueNDRangeKernel(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, KERNEL(0x1c5eb10)<0x18163d0>, 1, 0, 0x7fff4ee58c60, 0, NULL <0, 0>, {out}0x7fff4ee58aa8) = (ret: 0, *(0x7fff4ee58aa8): 0x18e0050)
clReleaseKernel(KERNEL(0x1c5eb10)<0x18163d0>) = (ret: 0)
clReleaseEvent(EVENT(0x1d39030)<0x18e0050>) = (ret: 0)
clGetMemObjectInfo(MEMORY_OBJECT(0x1c450e0)<0x1c0a7e0>, 4352, {out}<4, 0x7fff4ee58c20>, 0) = (ret: 0, *(0x7fff4ee58c20): 4336)
clEnqueueReadBuffer(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, MEMORY_OBJECT(0x1c450e0)<0x1c0a7e0>, true, 0, 524288, 0x1c6e240, NULL <0, 0>, {out}0x7fff4ee58d08) = (ret: 0, *(0x7fff4ee58d08): 0x180c970)
clGetEventInfo(EVENT(0x1bd4cc0)<0x180c970>, 4563, {out}<4, 0x7fff4ee58f8c>, 0) = (ret: 0, *(0x7fff4ee58f8c): 0)
clWaitForEvents(0x180c970 <1, 0x1bd4cc8>) = (ret: 0)
clReleaseEvent(EVENT(0x1bd4cc0)<0x180c970>) = (ret: 0)
clCreateBuffer(CONTEXT(0x122b760)<0x18c72e0>, 1, 524288, 0, {out}0x7fff4ee58f70) = (ret: 0x1cf4b60, *(0x7fff4ee58f70): 0)
clReleaseMemObject(MEMORY_OBJECT(0x1c450e0)<0x1c0a7e0>) = (ret: 0)
clCreateBuffer(CONTEXT(0x122b760)<0x18c72e0>, 36, 524288, 0x1839cb0, {out}0x7fff4ee58f70) = (ret: 0x1822220, *(0x7fff4ee58f70): 0)
clReleaseMemObject(MEMORY_OBJECT(0x18cf4d0)<0x182f1a0>) = (ret: 0)
clCreateKernel(PROGRAM(0x1c62d70)<0x18ccf10>, "square", {out}0x7fff4ee58b9c) = (ret: 0x1976cf0, *(0x7fff4ee58b9c): 0)
clGetKernelInfo(KERNEL(0x18cf4d0)<0x1976cf0>, 4497, {out}<4, 0x7fff4ee585d0>, 0) = (ret: 0, *(0x7fff4ee585d0): 3)
clGetKernelInfo(KERNEL(0x18cf4d0)<0x1976cf0>, 4496, 0, 0, {out}0x7fff4ee583d8) = (ret: 0, *(0x7fff4ee583d8): 7)
clGetKernelInfo(KERNEL(0x18cf4d0)<0x1976cf0>, 4496, {out}<7, 0x1d650e0>, {out}0x7fff4ee583d8) = (ret: 0, *(0x1d650e0): "square\0", *(0x7fff4ee583d8): 7)
clGetKernelInfo(KERNEL(0x18cf4d0)<0x1976cf0>, 4497, {out}<4, 0x7fff4ee58a50>, 0) = (ret: 0, *(0x7fff4ee58a50): 3)
clSetKernelArg(KERNEL(0x18cf4d0)<0x1976cf0>, 0, 0x1822220 <8, 0x1c450e8>) = (ret: 0)
clSetKernelArg(KERNEL(0x18cf4d0)<0x1976cf0>, 1, 0x1cf4b60 <8, 0x1838e68>) = (ret: 0)
clSetKernelArg(KERNEL(0x18cf4d0)<0x1976cf0>, 2, "\x0\x0\x0\x0" <4, 0x13b2f80>) = (ret: 0)
clEnqueueNDRangeKernel(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, KERNEL(0x18cf4d0)<0x1976cf0>, 1, 0, 0x7fff4ee58c60, 0, NULL <0, 0>, {out}0x7fff4ee58aa8) = (ret: 0, *(0x7fff4ee58aa8): 0x1d63f60)
clReleaseKernel(KERNEL(0x18cf4d0)<0x1976cf0>) = (ret: 0)
clReleaseEvent(EVENT(0x1b9f5c0)<0x1d63f60>) = (ret: 0)
clGetMemObjectInfo(MEMORY_OBJECT(0x1838e60)<0x1cf4b60>, 4352, {out}<4, 0x7fff4ee58c20>, 0) = (ret: 0, *(0x7fff4ee58c20): 4336)
clEnqueueReadBuffer(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, MEMORY_OBJECT(0x1838e60)<0x1cf4b60>, true, 0, 524288, 0x1c6e240, NULL <0, 0>, {out}0x7fff4ee58d08) = (ret: 0, *(0x7fff4ee58d08): 0x18e0050)
clGetEventInfo(EVENT(0x1c5eb10)<0x18e0050>, 4563, {out}<4, 0x7fff4ee58f8c>, 0) = (ret: 0, *(0x7fff4ee58f8c): 0)
clWaitForEvents(0x18e0050 <1, 0x1c5eb18>) = (ret: 0)
clReleaseEvent(EVENT(0x1c5eb10)<0x18e0050>) = (ret: 0)
clCreateBuffer(CONTEXT(0x122b760)<0x18c72e0>, 1, 524288, 0, {out}0x7fff4ee58f70) = (ret: 0x18c2150, *(0x7fff4ee58f70): 0)
clReleaseMemObject(MEMORY_OBJECT(0x1838e60)<0x1cf4b60>) = (ret: 0)
clCreateBuffer(CONTEXT(0x122b760)<0x18c72e0>, 36, 524288, 0x1839cb0, {out}0x7fff4ee58f70) = (ret: 0x1c67350, *(0x7fff4ee58f70): 0)
clReleaseMemObject(MEMORY_OBJECT(0x1c450e0)<0x1822220>) = (ret: 0)
clCreateKernel(PROGRAM(0x1c62d70)<0x18ccf10>, "square", {out}0x7fff4ee58b9c) = (ret: 0x1c16ea0, *(0x7fff4ee58b9c): 0)
clGetKernelInfo(KERNEL(0x1c450e0)<0x1c16ea0>, 4497, {out}<4, 0x7fff4ee585d0>, 0) = (ret: 0, *(0x7fff4ee585d0): 3)
clGetKernelInfo(KERNEL(0x1c450e0)<0x1c16ea0>, 4496, 0, 0, {out}0x7fff4ee583d8) = (ret: 0, *(0x7fff4ee583d8): 7)
clGetKernelInfo(KERNEL(0x1c450e0)<0x1c16ea0>, 4496, {out}<7, 0x1813b50>, {out}0x7fff4ee583d8) = (ret: 0, *(0x1813b50): "square\0", *(0x7fff4ee583d8): 7)
clGetKernelInfo(KERNEL(0x1c450e0)<0x1c16ea0>, 4497, {out}<4, 0x7fff4ee58a50>, 0) = (ret: 0, *(0x7fff4ee58a50): 3)
clSetKernelArg(KERNEL(0x1c450e0)<0x1c16ea0>, 0, 0x1c67350 <8, 0x1838e68>) = (ret: 0)
clSetKernelArg(KERNEL(0x1c450e0)<0x1c16ea0>, 1, 0x18c2150 <8, 0x1c5ff68>) = (ret: 0)
clSetKernelArg(KERNEL(0x1c450e0)<0x1c16ea0>, 2, "\x0\x0\x0\x0" <4, 0x13b2f80>) = (ret: 0)
clEnqueueNDRangeKernel(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, KERNEL(0x1c450e0)<0x1c16ea0>, 1, 0, 0x7fff4ee58c60, 0, NULL <0, 0>, {out}0x7fff4ee58aa8) = (ret: 0, *(0x7fff4ee58aa8): 0x180c970)
clReleaseKernel(KERNEL(0x1c450e0)<0x1c16ea0>) = (ret: 0)
clReleaseEvent(EVENT(0x1d39030)<0x180c970>) = (ret: 0)
clGetMemObjectInfo(MEMORY_OBJECT(0x1c5ff60)<0x18c2150>, 4352, {out}<4, 0x7fff4ee58c20>, 0) = (ret: 0, *(0x7fff4ee58c20): 4336)
clEnqueueReadBuffer(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, MEMORY_OBJECT(0x1c5ff60)<0x18c2150>, true, 0, 524288, 0x1c6e240, NULL <0, 0>, {out}0x7fff4ee58d08) = (ret: 0, *(0x7fff4ee58d08): 0x1d63f60)
clGetEventInfo(EVENT(0x18cf4d0)<0x1d63f60>, 4563, {out}<4, 0x7fff4ee58f8c>, 0) = (ret: 0, *(0x7fff4ee58f8c): 0)
clWaitForEvents(0x1d63f60 <1, 0x18cf4d8>) = (ret: 0)
clReleaseEvent(EVENT(0x18cf4d0)<0x1d63f60>) = (ret: 0)
clCreateBuffer(CONTEXT(0x122b760)<0x18c72e0>, 1, 524288, 0, {out}0x7fff4ee58f70) = (ret: 0x1c0a7e0, *(0x7fff4ee58f70): 0)
clReleaseMemObject(MEMORY_OBJECT(0x1c5ff60)<0x18c2150>) = (ret: 0)
clCreateBuffer(CONTEXT(0x122b760)<0x18c72e0>, 36, 524288, 0x1839cb0, {out}0x7fff4ee58f70) = (ret: 0x182f1a0, *(0x7fff4ee58f70): 0)
clReleaseMemObject(MEMORY_OBJECT(0x1838e60)<0x1c67350>) = (ret: 0)
clCreateKernel(PROGRAM(0x1c62d70)<0x18ccf10>, "square", {out}0x7fff4ee58b9c) = (ret: 0x1c4ebe0, *(0x7fff4ee58b9c): 0)
clGetKernelInfo(KERNEL(0x1838e60)<0x1c4ebe0>, 4497, {out}<4, 0x7fff4ee585d0>, 0) = (ret: 0, *(0x7fff4ee585d0): 3)
clGetKernelInfo(KERNEL(0x1838e60)<0x1c4ebe0>, 4496, 0, 0, {out}0x7fff4ee583d8) = (ret: 0, *(0x7fff4ee583d8): 7)
clGetKernelInfo(KERNEL(0x1838e60)<0x1c4ebe0>, 4496, {out}<7, 0x1d650e0>, {out}0x7fff4ee583d8) = (ret: 0, *(0x1d650e0): "square\0", *(0x7fff4ee583d8): 7)
clGetKernelInfo(KERNEL(0x1838e60)<0x1c4ebe0>, 4497, {out}<4, 0x7fff4ee58a50>, 0) = (ret: 0, *(0x7fff4ee58a50): 3)
clSetKernelArg(KERNEL(0x1838e60)<0x1c4ebe0>, 0, 0x182f1a0 <8, 0x1c5ff68>) = (ret: 0)
clSetKernelArg(KERNEL(0x1838e60)<0x1c4ebe0>, 1, 0x1c0a7e0 <8, 0x1bd4cc8>) = (ret: 0)
clSetKernelArg(KERNEL(0x1838e60)<0x1c4ebe0>, 2, "\x0\x0\x0\x0" <4, 0x13b2f80>) = (ret: 0)
clEnqueueNDRangeKernel(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, KERNEL(0x1838e60)<0x1c4ebe0>, 1, 0, 0x7fff4ee58c60, 0, NULL <0, 0>, {out}0x7fff4ee58aa8) = (ret: 0, *(0x7fff4ee58aa8): 0x18e0050)
clReleaseKernel(KERNEL(0x1838e60)<0x1c4ebe0>) = (ret: 0)
clReleaseEvent(EVENT(0x1b9f5c0)<0x18e0050>) = (ret: 0)
clGetMemObjectInfo(MEMORY_OBJECT(0x1bd4cc0)<0x1c0a7e0>, 4352, {out}<4, 0x7fff4ee58c20>, 0) = (ret: 0, *(0x7fff4ee58c20): 4336)
clEnqueueReadBuffer(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>, MEMORY_OBJECT(0x1bd4cc0)<0x1c0a7e0>, true, 0, 524288, 0x1c6e240, NULL <0, 0>, {out}0x7fff4ee58d08) = (ret: 0, *(0x7fff4ee58d08): 0x180c970)
clGetEventInfo(EVENT(0x1c450e0)<0x180c970>, 4563, {out}<4, 0x7fff4ee58f8c>, 0) = (ret: 0, *(0x7fff4ee58f8c): 0)
clWaitForEvents(0x180c970 <1, 0x1c450e8>) = (ret: 0)
clReleaseEvent(EVENT(0x1c450e0)<0x180c970>) = (ret: 0)
Iteration 0. Still alive
Iteration 99. Still alive
Iteration 198. Still alive
Iteration 297. Still alive
Iteration 396. Still alive
Iteration 495. Still alive
Iteration 594. Still alive
Iteration 693. Still alive
Iteration 792. Still alive
Iteration 891. Still alive
Iteration 990. Still alive
Iteration 1089. Still alive
Iteration 1188. Still alive
Iteration 1287. Still alive
Iteration 1386. Still alive
Iteration 1485. Still alive
Iteration 1584. Still alive
Iteration 1683. Still alive
Iteration 1782. Still alive
Iteration 1881. Still alive
Iteration 1980. Still alive
Iteration 2079. Still alive
Iteration 2178. Still alive
Iteration 2277. Still alive
Iteration 2376. Still alive
Iteration 2475. Still alive
Iteration 2574. Still alive
Iteration 2673. Still alive
Iteration 2772. Still alive
Iteration 2871. Still alive
Iteration 2970. Still alive
Iteration 3069. Still alive
Iteration 3168. Still alive
Iteration 3267. Still alive
Iteration 3366. Still alive
Iteration 3465. Still alive
Iteration 3564. Still alive
Iteration 3663. Still alive
Iteration 3762. Still alive
Iteration 3861. Still alive
Iteration 3960. Still alive
Iteration 4059. Still alive
Iteration 4158. Still alive
Iteration 4257. Still alive
Iteration 4356. Still alive
Iteration 4455. Still alive
Iteration 4554. Still alive
Iteration 4653. Still alive
Iteration 4752. Still alive
Iteration 4851. Still alive
Iteration 4950. Still alive
Iteration 5049. Still alive
Iteration 5148. Still alive
Iteration 5247. Still alive
Iteration 5346. Still alive
Iteration 5445. Still alive
Iteration 5544. Still alive
Iteration 5643. Still alive
Iteration 5742. Still alive
Iteration 5841. Still alive
Iteration 5940. Still alive
Iteration 6039. Still alive
Iteration 6138. Still alive
Iteration 6237. Still alive
Iteration 6336. Still alive
Iteration 6435. Still alive
Iteration 6534. Still alive
Iteration 6633. Still alive
Iteration 6732. Still alive
Iteration 6831. Still alive
Iteration 6930. Still alive
Iteration 7029. Still alive
Iteration 7128. Still alive
Iteration 7227. Still alive
Iteration 7326. Still alive
Iteration 7425. Still alive
Iteration 7524. Still alive
Iteration 7623. Still alive
Iteration 7722. Still alive
Iteration 7821. Still alive
Iteration 7920. Still alive
Iteration 8019. Still alive
Iteration 8118. Still alive
Iteration 8217. Still alive
Iteration 8316. Still alive
Iteration 8415. Still alive
Iteration 8514. Still alive
Iteration 8613. Still alive
Iteration 8712. Still alive
Iteration 8811. Still alive
Iteration 8910. Still alive
Iteration 9009. Still alive
Iteration 9108. Still alive
Iteration 9207. Still alive
Iteration 9306. Still alive
Iteration 9405. Still alive
Iteration 9504. Still alive
Iteration 9603. Still alive
Iteration 9702. Still alive
Iteration 9801. Still alive
Iteration 9900. Still alive
clReleaseMemObject(MEMORY_OBJECT(0x1c5ff60)<0x182f1a0>) = (ret: 0)
clReleaseCommandQueue(COMMAND_QUEUE(0x17f6c60)<0x17f1ed0>) = (ret: 0)
clReleaseProgram(PROGRAM(0x1c62d70)<0x18ccf10>) = (ret: 0)
clReleaseMemObject(MEMORY_OBJECT(0x1bd4cc0)<0x1c0a7e0>) = (ret: 0)
clReleaseContext(CONTEXT(0x122b760)<0x18c72e0>) = (ret: 0)
peak memory used: 112001024

**Comment by inducer** [comment]
To the best of my knowledge, the behavior of the wrapper shouldn't change based on whether tracing is enabled. The reason I wanted the (full, not partial) trace log is to make sure we issue a balanced number of `clCreate/RetainBuffer` and `clReleaseBuffer` calls.

**Comment by inferrna** [comment]
inferno@inferno-X550LA:~/.dev/OpenCL$ egrep -a clReleaseMem leaklog.txt |wc
-l
19998
inferno@inferno-X550LA:~/.dev/OpenCL$ egrep -a clCreateBuffer\|RetainBuffer
leaklog.txt |wc -l
19998


2015-08-26 11:19 GMT+08:00 Andreas Klöckner <notifications@github.com>:

**Comment by inferrna** [comment]
I have added  ```cl.enqueue_barrier(queue)``` before ```assert``` into leaktest.py and changes have occurred

**Without barrier:**
inferno@inferno-X550LA:~/.dev/OpenCL$ time limitmemory 256M python3 leaktest.py
limiting memory to 256M (cgroup limitmem_25508) for command python3 leaktest.py
Iteration 0. Still alive
Iteration 99. Still alive
Iteration 198. Still alive
Iteration 297. Still alive
Iteration 396. Still alive
Iteration 495. Still alive
Iteration 594. Still alive
Iteration 693. Still alive
Iteration 792. Still alive
Iteration 891. Still alive
Iteration 990. Still alive
Iteration 1089. Still alive
Iteration 1188. Still alive
Iteration 1287. Still alive
Iteration 1386. Still alive
Iteration 1485. Still alive
Iteration 1584. Still alive
Killed
peak memory used: 268435456

real	0m8.123s
user	0m4.095s
sys	**0m3.862s**

**With barrier:**
inferno@inferno-X550LA:~/.dev/OpenCL$ time limitmemory 256M python3 leaktest.py
limiting memory to 256M (cgroup limitmem_24619) for command python3 leaktest.py
Iteration 0. Still alive
Iteration 99. Still alive
Iteration 198. Still alive
Iteration 297. Still alive
Iteration 396. Still alive
Iteration 495. Still alive
Iteration 594. Still alive
Iteration 693. Still alive
Iteration 792. Still alive
Iteration 891. Still alive
Iteration 990. Still alive
Iteration 1089. Still alive
Iteration 1188. Still alive
Iteration 1287. Still alive
Iteration 1386. Still alive
Iteration 1485. Still alive
Iteration 1584. Still alive
Iteration 1683. Still alive
Iteration 1782. Still alive
Iteration 1881. Still alive
Iteration 1980. Still alive
peak memory used: 30765056

real	0m5.543s
user	0m5.077s
sys	**0m0.406s**

With barrier it runs really faster.

**Comment by inducer** [comment]
This is kind of strange. To my mind, this indicates that there is really something wrong with beignet. I imagine what the berries help it do is keep the GPU's Q from filling up all the way. But then, it shouldn't let that happen anyway. If something about it starts performing poorly soon as the queue fills up, maybe it shouldn't let that happen.

At any rate, I can't really imagine how PyOpenCL would contribute to or have anything to do with this behavior.

**Comment by inferrna** [comment]
Confirmed as an beignet issue, working patch is out.
