### ISSUE TITLE
Compilation terminated, cannon open source file

### ISSUE THREAD

**Issue by RyanHope** [pyopencl/pyopencl#90]
I have 2 kernels that both share a common helper function which I abstracted out into a helper file which then gets #included... This seems to work fine on my OSX system using the stock Apple OpenCL compiler/library but on a different Windows 10 both with the AMD OpenCL compiler/library I get a cannon open source file error. Basically, the compiler can't find the header. How do I tell pyopencl where to look for headers?

**Comment by inducer** [comment]
`-I` in the `build()` options. Next time, please do not use this issue tracker to request assistance with support issues.

**Comment by RyanHope** [comment]
The fact that it needs zero extra options on one system and not the other
seems like a bug.

On Mon, Aug 31, 2015 at 11:19 PM, Andreas Klöckner <notifications@github.com
> wrote:

> Closed #90 <https://github.com/pyopencl/pyopencl/issues/90>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyopencl/pyopencl/issues/90#event-397346170>.
>



-- 
Ryan Hope, M.S.
CogWorks Lab
Cognitive Science Department
Rensselaer Polytechnic Institute

**Comment by inducer** [comment]
Sorry, I understand now where you are coming from in terms of saying that this could conceivably be a bug in PyOpenCL. As a matter of fact though, what you're seeing is just don't implementation differences between different OpenCL drivers (ICDs). As such, there is unfortunately little that PyOpenCL can do. In your situation though, it should be safe to simply pass a `-I` option pointing to the directory where your header resides, and you should be fine across all OpenCL platforms.
