### ISSUE TITLE
Add support for clBLAS and others.

### ISSUE THREAD

**Issue by inferrna** [pyopencl/pyopencl#91]
It would be great to add support for AMD's clBLAS and optionally clFFT libraries. There is almost nothing to do: functions requires same OpenCL arguments as clEnqueueKernel. Example:
https://github.com/clMathLibraries/clBLAS/blob/master/src/samples/example_sdot.c#LC117

But it needed some prepare calling. For clBLAS:  https://github.com/clMathLibraries/clBLAS/blob/master/src/samples/example_sdot.c#LC97
For clFFT: https://github.com/clMathLibraries/clFFT/blob/develop/src/examples/fft3d.c#LC66
As of my opinion it would be better to keep its results in some kind of cache to avoid overhead. I have no any idea how to implement it - I'm noob in C/C++ tricks

**Comment by inducer** [comment]
http://documen.tician.de/pyopencl/#software-that-works-with-or-enhances-pyopencl
