### ISSUE TITLE
Problem with GL interop on Mac OSX

### ISSUE THREAD

**Issue by grahamrow** [pyopencl/pyopencl#96]
I'm having trouble establishing a shared context, specifically the expected flags aren't found when running get_gl_sharing_context_properties(). I ran examples/gl_interop_demo.py in both Python 2.7 and 3.5 with the same results. These are brew installed pythons on Mac OSX 10.10.5. I'm on a MacBook with integrated and discrete graphics, which I would expect could lead to some confusion.

Traceback (most recent call last):
  File "gl.py", line 80, in <module>
    initialize()
  File "gl.py", line 28, in initialize
    ctx = cl.Context(properties=get_gl_sharing_context_properties(),
  File "/usr/local/lib/python3.5/site-packages/pyopencl/tools.py", line 422, in get_gl_sharing_context_properties
    (ctx_props.CONTEXT_PROPERTY_USE_CGL_SHAREGROUP_APPLE,
AttributeError: type object 'context_properties' has no attribute 'CONTEXT_PROPERTY_USE_CGL_SHAREGROUP_APPLE'

**Comment by inducer** [comment]
Did you build PyOpenCL with `CL_ENABLE_GL = True`? (Run `configure.py` and look at `siteconf.py`.)

**Comment by grahamrow** [comment]
Thanks Andreas, I'd assumed this was built by default for whatever reason. Ran `python configure.py --cl-enable-gl` and then `pip3 install -e .' within the working directory. Now works perfectly, thanks for the great software.

**Comment by MeisterNewman** [comment]
Basic question, but how do I build it like that? I can't seem to find configure.py.

Thanks for the help!

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

If you download the tarball from [here](https://pypi.org/project/pyopencl/#files), there's `configure.py` in there. (I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
