### ISSUE TITLE
Impossible to explicitly choose cache_dir

### ISSUE THREAD

**Issue by PolarNick239** [pyopencl/pyopencl#97]
Use case:
`cl.array.zeros(cl_queue, (h, w, 2), np.float32)`
Exception:
`PermissionError: [Errno 13] Permission denied: '/.cache'`

PyOpenCL will implicitly use as cache dir `os.getenv('XDG_CACHE_HOME', os.path.expanduser('~/.cache'))`, but my server is a daemon, so $HOME is empty, so it tries to use '/.cache' directory, but of course it has no rights, and so it fails. 
(`cache_dir = join(appdirs.user_cache_dir("pyopencl", "pyopencl"),` https://github.com/pyopencl/pyopencl/blob/master/pyopencl/cache.py#L345)

**Suggestion**: provide possibility to choose cache dir explicitly. May be the best way is not `Program.build(..., cache_dir)`, but make cache_dir be an optional property of context? Because it is impossible to configure cache_dir for such places: 
(`return Program(context, source).build(options)` https://github.com/pyopencl/pyopencl/blob/master/pyopencl/elementwise.py#L111)

**Workaround**:
`export XDG_CACHE_HOME="/home/<user_name>/.cache"`

**Comment by inducer** [comment]
I like the idea of configuring the cache directory per-context. Could you hack together a patch?

**Comment by PolarNick239** [comment]
Yes, but not very soon - in a couple of weeks.

**Comment by inducer** [comment]
Sounds good. Let me know if you run into any unexpected obstacles.

**Comment by inducer** [comment]
Looks like this is taken care of. Thanks again for your contribution!
